import { useParams, useNavigate, Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  ArrowLeft,
  FileText,
  Shield,
  Scale,
  DollarSign,
  Stethoscope,
  Gavel,
  Handshake,
  AlertTriangle,
  HelpCircle,
  ListChecks,
  Copy,
  Download,
  Archive,
  Loader2,
  CalendarDays,
  MapPin,
  Briefcase,
  Hash,
} from "lucide-react";
import ReviewSection from "@/components/claims/ReviewSection";
import StatusBadge from "@/components/claims/StatusBadge";
import ConfidenceBadge from "@/components/claims/ConfidenceBadge";
import { format } from "date-fns";
import { toast } from "@/components/ui/use-toast";

const sections = [
  { key: "executive_summary", title: "Executive Summary", icon: FileText, accent: "bg-primary" },
  { key: "coverage_summary", title: "Coverage Summary", icon: Shield, accent: "bg-blue-600" },
  { key: "liability_summary", title: "Liability Summary", icon: Scale, accent: "bg-indigo-600" },
  { key: "damages_summary", title: "Damages Summary", icon: DollarSign, accent: "bg-emerald-600" },
  { key: "medical_treatment_summary", title: "Medical Treatment Summary", icon: Stethoscope, accent: "bg-teal-600" },
  { key: "litigation_status", title: "Litigation Status", icon: Gavel, accent: "bg-purple-600" },
  { key: "settlement_posture", title: "Settlement Posture", icon: Handshake, accent: "bg-sky-600" },
  { key: "red_flags", title: "Red Flags", icon: AlertTriangle, accent: "bg-red-600" },
  { key: "missing_information", title: "Missing Information", icon: HelpCircle, accent: "bg-amber-600" },
  { key: "recommended_next_steps", title: "Recommended Next Steps", icon: ListChecks, accent: "bg-green-600" },
];

export default function ClaimReviewResults() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const { data: review, isLoading } = useQuery({
    queryKey: ["claimReview", id],
    queryFn: async () => {
      const reviews = await base44.entities.ClaimReview.filter({ id });
      return reviews[0];
    },
  });

  const archiveMutation = useMutation({
    mutationFn: () => base44.entities.ClaimReview.update(id, { status: "archived" }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["claimReview", id] });
      toast({ title: "Review archived" });
    },
  });

  const copyToClipboard = () => {
    if (!review) return;
    const text = sections
      .map((s) => {
        const content = review[s.key];
        return content ? `## ${s.title}\n${content}` : null;
      })
      .filter(Boolean)
      .join("\n\n");

    const header = `CLAIM REVIEW REPORT
Claim: ${review.claim_name}
Claim #: ${review.claim_number}
Date of Loss: ${review.date_of_loss}
Jurisdiction: ${review.jurisdiction}
Line of Business: ${review.line_of_business}
Confidence Level: ${review.confidence_level || "N/A"}
Generated: ${review.created_date ? format(new Date(review.created_date), "MMMM d, yyyy") : "N/A"}
${"=".repeat(60)}

`;

    navigator.clipboard.writeText(header + text);
    toast({ title: "Copied to clipboard", description: "Full review text has been copied." });
  };

  const exportReport = () => {
    if (!review) return;
    const text = sections
      .map((s) => {
        const content = review[s.key];
        return content ? `${"=".repeat(60)}\n${s.title.toUpperCase()}\n${"=".repeat(60)}\n\n${content}\n` : null;
      })
      .filter(Boolean)
      .join("\n");

    const header = `${"=".repeat(60)}
CLAIM REVIEW REPORT
${"=".repeat(60)}

Claim Name: ${review.claim_name}
Claim Number: ${review.claim_number}
Date of Loss: ${review.date_of_loss}
Jurisdiction: ${review.jurisdiction}
Line of Business: ${review.line_of_business}
Confidence Level: ${review.confidence_level || "N/A"}
Report Generated: ${review.created_date ? format(new Date(review.created_date), "MMMM d, yyyy 'at' h:mm a") : "N/A"}

DISCLAIMER: This report is generated by an AI assistant for educational and portfolio purposes only. It is not legal advice and should not be used for actual claims handling decisions.

`;

    const blob = new Blob([header + text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Claim_Review_${review.claim_number || "report"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Report exported", description: "Text file downloaded." });
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-24">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!review) {
    return (
      <div className="text-center py-24">
        <p className="text-muted-foreground">Review not found.</p>
        <Link to="/"><Button variant="outline" className="mt-4">Back to Dashboard</Button></Link>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-4xl mx-auto pb-12">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="mt-1 shrink-0">
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <div className="flex items-center gap-2.5 flex-wrap">
              <h1 className="font-heading text-2xl md:text-3xl font-bold tracking-tight">{review.claim_name}</h1>
              <StatusBadge status={review.status} />
            </div>
            <div className="flex items-center gap-4 mt-2 flex-wrap">
              <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <Hash className="w-3 h-3" />{review.claim_number}
              </span>
              <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <CalendarDays className="w-3 h-3" />{review.date_of_loss}
              </span>
              <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <MapPin className="w-3 h-3" />{review.jurisdiction}
              </span>
              <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <Briefcase className="w-3 h-3" />{review.line_of_business}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Action Bar */}
      <Card className="shadow-sm">
        <CardContent className="p-4 flex items-center justify-between flex-wrap gap-3">
          <ConfidenceBadge level={review.confidence_level} />
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={copyToClipboard}>
              <Copy className="w-3.5 h-3.5 mr-1.5" />Copy
            </Button>
            <Button variant="outline" size="sm" onClick={exportReport}>
              <Download className="w-3.5 h-3.5 mr-1.5" />Export
            </Button>
            {review.status !== "archived" && (
              <Button variant="outline" size="sm" onClick={() => archiveMutation.mutate()} disabled={archiveMutation.isPending}>
                <Archive className="w-3.5 h-3.5 mr-1.5" />Archive
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Review Sections */}
      <div className="space-y-4">
        {sections.map((s) => (
          <ReviewSection
            key={s.key}
            title={s.title}
            icon={s.icon}
            content={review[s.key]}
            accentColor={s.accent}
          />
        ))}
      </div>

      {/* Reviewer Notes */}
      {review.reviewer_notes && (
        <Card className="shadow-sm border-dashed">
          <CardHeader className="pb-3">
            <CardTitle className="text-base text-muted-foreground">Reviewer Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground italic">{review.reviewer_notes}</p>
          </CardContent>
        </Card>
      )}

      {/* Disclaimer */}
      <div className="text-center py-6 border-t">
        <p className="text-[11px] text-muted-foreground max-w-lg mx-auto leading-relaxed">
          This report was generated by an AI assistant and is for educational and portfolio purposes only.
          It does not constitute legal advice. All analysis is based on the claim file text provided.
        </p>
      </div>
    </div>
  );
}