import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export default function TermsOfUse() {
  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div>
        <h1 className="font-heading text-2xl md:text-3xl font-bold tracking-tight">Terms of Use</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Terms and conditions for using ClaimIntel
        </p>
        <p className="text-xs text-muted-foreground mt-2">Last updated: June 2026</p>
      </div>

      <Card className="shadow-sm border-amber-200 bg-amber-50/50">
        <CardContent className="py-4">
          <p className="text-sm text-amber-900 font-medium leading-relaxed">
            ClaimIntel is currently in beta. Do not upload confidential, privileged, medical, legal, or personally identifiable claim information unless you are authorized to do so and understand your organization's privacy, confidentiality, and regulatory obligations.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">1. Acceptance of Terms</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By accessing and using ClaimIntel, you accept and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the platform.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">2. Beta Program</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            ClaimIntel is currently in beta. Beta users receive two complimentary AI-powered claim reviews. After two completed reviews, additional reviews require an upgrade to a Professional or Enterprise plan. Beta users are limited to ten saved reports. Features and functionality may change during the beta period.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">3. Educational & Demonstration Purpose</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            ClaimIntel is an AI-powered tool designed to assist insurance professionals with claim file analysis and documentation. The platform generates structured summaries based solely on the documents provided. It does not provide legal advice and does not create an attorney-client relationship. Actual claims handling decisions should be made by qualified professionals.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">4. User Responsibilities</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You are responsible for ensuring that any information you upload complies with your organization's data handling policies, confidentiality obligations, and applicable laws. Do not upload confidential, privileged, medical, legal, or personally identifiable information unless you are authorized to do so. Use only fictional or sample data for testing purposes during the beta program.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">5. AI-Generated Content</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            All reports generated by ClaimIntel are produced by AI based on the documents you provide. The AI only uses facts found in those documents and does not create facts or make assumptions. Reports include source references and clearly separate factual findings from recommendations. All outputs include a watermark indicating they were generated during the ClaimIntel Beta.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">6. Account Security</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You are responsible for maintaining the security of your account credentials. Authentication is required for all platform access. Do not share your login credentials. All actions performed under your account are recorded in the audit log. Report any unauthorized access immediately.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">7. Data & Privacy</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Your data is stored securely and isolated to your account. Each user can only access their own files and reports. You may request deletion of your account data at any time through Settings. See our Privacy Policy for full details.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">8. Limitation of Liability</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            ClaimIntel is provided "as is" without warranties of any kind. The platform is a beta-stage product and may contain errors or inaccuracies. ClaimIntel is not liable for any decisions made based on AI-generated reports. Users should verify all findings with qualified professionals.
          </p>
        </CardContent>
      </Card>

      <Separator />

      <div className="text-center pb-8">
        <p className="text-xs text-muted-foreground">ClaimIntel © 2026 — Smarter Claims. Better Decisions.</p>
        <p className="text-xs text-muted-foreground mt-0.5">Educational & Portfolio Prototype</p>
      </div>
    </div>
  );
}